### PR TITLE
Create autspaces-ia-diagram-15-11-2021

### PR DESCRIPTION
**Pull request by soledadli**

### CODE REVIEW

**Review by BrainonSilicon — CHANGES_REQUESTED** [review]
Awesome @soledadli! Let's figure out how to embedd the diagram into this file and then we can merge it 👩‍💻

**Comment by BrainonSilicon** [comment]
Hi @soledadli  - I see that you updated this in your other PR so I'll close this one and accept the newer PR 🌟

**Comment by BrainonSilicon** [comment]
I'm going to reopen this branch and merge it based on the png file that @soledadli added to the parent folder.

**Comment by soledadli** [comment]
@BrainonSilicon Hi Sophia. You may need to reopen this one. The other new request is to add the IA image. This one is to add the README.

**Review by BrainonSilicon — CHANGES_REQUESTED** [review]
Hi @soledadli 

Can you add a .md to the end of the file name so that the file is recognized as Markdown?

**Comment by soledadli** [comment]
.md is added. The name is so long that I forgot to add it. Thanks for pointing it out! @BrainonSilicon

**Review by BrainonSilicon — APPROVED** [review]
Awesome! 

Should be good to go now :)

**Pull request merged**
