### PR TITLE
Lottycoupat roadmap

### PR DESCRIPTION
**Pull request by lottycoupat**

### CODE REVIEW

**Comment by lottycoupat** [comment]
Roadmap documentation uploaded.

**Review by sowmya9507 — COMMENTED** [review]
Everything looks perfect

**Review by anoura12 — APPROVED** [review]
Yep. This looks good!

**Review by GeorgiaHCA — APPROVED** [review]
This looks awesome @lottycoupat - happy for you to go agead and merge!! 👍

**Pull request merged**
