### PR TITLE
Lottycoupat newsletter apr/may

### PR DESCRIPTION
**Pull request by lottycoupat**
Would love a review of this months news letter please!

### CODE REVIEW

**Review by KirstieJane — APPROVED** [review]
This looks great! The only thing that's missing is a contact email for @sowmya9507.

Sowmya - can you confirm that you're ok to put your email address in the newsletter? If not then you can make it clear that the best path is for commuity members to email @lottycoupat and then she'll put y'all in touch :)

**Comment by sowmya9507** [comment]
@KirstieJane It is totally okay for me to share my email in the newsletter! Thank you for checking 😄

**Comment by KirstieJane** [comment]
Thanks @sowmya9507 that's great.

In future, can you leave merging the pull request to the person who opened it? I don't want @lottycoupat to miss the action to add in the email addresses thinking that the approval meant there were no additional tasks.

**Comment by sowmya9507** [comment]
@KirstieJane Sure, I am so sorry. I was thinking there was pull request for each member that has to be confirmed. I will be definitely careful next time.

**Pull request merged**
