### PR TITLE
Fix Non-Welcoming WelcomeBot

### PR DESCRIPTION
**Pull request by jhlink**
# Changes

- Indent config.yaml file. Apparently, comments need to be strictly aligned.

# Details
After merging the change, please delete issue #224. Afterwards, I can create a new issue as a bonafide newcomer to confirm the fix.

### CODE REVIEW

**Comment by GeorgiaHCA** [comment]
WOAH!!!!!!!!!! That's cool! Amazing @jhlink and @malvikasharan - your work is profoundly appreciated and it was fun to solve the puzzle! 🌟 🏆 stars and trophies all round @Ismael-KG and @sgibson91 thought you might be please to know we have a bot miracle worker who finally solved the puzzle.

**Comment by sgibson91** [comment]
AMAZING! 💖💖💖🎉🎉🎉 I _knew_ it'd be whitespacing, I just couldn't spot it. THANK YOU.

**Comment by jhlink** [comment]
Happy to help! 😄

**Comment by Ismael-KG** [comment]
Hooray!!!

**Pull request merged**
