### PR TITLE
Fixing the all-contributors badge

### PR DESCRIPTION
**Pull request by sgibson91**
The PR adds in some missing spec from the all-contributors badge in the readme. Hopefully this means that it will now automatically update when new contributors are added!

### CODE REVIEW

**Comment by sgibson91** [comment]
> LGTM! The one thing I'm not 100% sure about is whether we need to also specify the badge template in the config (c.f. https://allcontributors.org/docs/en/bot/configuration), as that's currently not done? 🙂

My guess based on the Turing Way's implementation of the bot is yes, it's needed https://github.com/alan-turing-institute/the-turing-way/blob/efab71950e58f5c51bef9b6465659fd864ad369c/.all-contributorsrc#L7

**Comment by gedankenstuecke** [comment]
Do you want to add it or should I make a quick PR for that? :)

**Comment by sgibson91** [comment]
I'm busy right now, but can push a commit this afternoon :)

**Comment by sgibson91** [comment]
Config file updated!

**Pull request merged**
