### PR TITLE
September newsletter

### PR DESCRIPTION
**Pull request by GeorgiaHCA**
Suggestion for September newsletter. There's a lot more information and links which could be included, but I've tried to make it clear and precise after the feedback from the last one. Any thoughts appreciated :-D

Georgia

### CODE REVIEW

**Comment by GeorgiaHCA** [comment]
We could also include the link to the Gitter apps (https://gitter.im/apps) in the September newsletter if people want to interact this way and to make it easier to use by phone. What do you reckon @SuziQpid and @KirstieJane?  Or is that too much information to include, and is it better to have a single channel for simplicity (the survey).

G

**Comment by SuziQpid** [comment]
Dear All,

Yes l think you should quote the gitter hub links in the September
newsletter. It will mean a 'portable' portal for busy participants in the
thick of experiencing some pretty awful ambient environs but it shouldn't
confuse the main nerd herd who already understand which option is which. If
someone could create a visual communication flow chart for the research
platforms in the newsletter that would be absolutely a charm.

One that illustrates the door/ portal  youre entering from and where your
information will be received, a hint at some of its onward journey and
where the repository ends / starts to become transferable data into a
report/ stats.

I don't know whether you can follow my convoluted attempt at helping
explain the problem we technophobes have in realising how best to
communicate with those of you who speak this supernova language.

Cheers
Sue.

**Comment by GeorgiaHCA** [comment]
This is great feedback thanks! I'll have a shot at drafting a flow chart diagram by the end of the week and share it. Let me know if it helps

**Comment by GeorgiaHCA** [comment]
I could add the flowchart to the GitHub, maybe? I agree it would be good to get the newsletter out soon - especially if we're asking for ideas for the focus groups.

**Comment by GeorgiaHCA** [comment]
Although that doesn't solve the problem if GitHub is a barrier to people

**Comment by KirstieJane** [comment]
Yep - sounds like a great plan!!

**Comment by SuziQpid** [comment]
Dear All,

I'm wholly reliant on your more sensible approach. I wrongly made the
assumption that the debuggers were already working on the 'gittery ' bits
of the app!

Of course it takes time. Aren't the impatient ones always the ones NOT
actually finding the solution. Yes get the newsletter out. Will that
contain links to the first survey or just be outlining the process. ?

Also don't mean to moan yet again but when will we get the link to the
uploaded Pint of Science panel we all took part in. I'm being nagged by my
sons about it.

In deference to the greater IT architects in the works
Sue.

**Comment by KirstieJane** [comment]
Hi @SuziQpid!! I'll chase the events team at the Turing for the video!

And thank you so much again for the feedback 💖

**Comment by KirstieJane** [comment]
> OS comments:
> Like the bullet points

Argh - I just reformatted the newsletter to get rid of the bullet points....but I did put in sub headings?? Do you think that will be helpful?
 
> Reads well
> Link to Open Humans: would be useful to link to the demo itself? (GA: need to clarify technical knowledge required)

I've added this in but tried to make it clear that its really confusing....what do you think?

> Survey could use more of an example - maybe show a clip of something (animated?) - more of a guide of the kind of answer people may be looking for - tool or pathway

Yes....for sure. But I think its more important that we get this update sent and improve the survey as discussed in #41. What do you think @GeorgiaHCA?

**Pull request merged**
