### PR TITLE
Create backlog-refinement-2020-03-31.md

### PR DESCRIPTION
**Pull request by GeorgiaHCA**
This adds organised notes from the backlog refinement meeting on 31st March 2020
@driscolle I have a list of attendees I can email you - would you be able to check if they are happy having their names and GitHub IDs published here? They added it themselves to the original HackMd, so I guess they would be fine, but best to double check and totally okay to keep it anonymous if preferred!

### CODE REVIEW

**Comment by driscolle** [comment]
Hi, no issues.

Emilia Driscoll
Project Manager
MIS - Solution Implementation Directorate
Fujitsu
Mob: +44 (0) 7867821962 or Internally 73 821962
Email: Emilia.Driscoll@uk.fujitsu.com<mailto:firstname.surname@xx.fujitsu.com>
Web: uk.fujitsu.com<http://uk.fujitsu.com/>
[youtube-icon.gif]<http://www.youtube.com/user/fujitsuUK> [Facebook-icon.gif] <http://www.facebook.com/fujitsuuk>  [twitter-icon.gif] <http://twitter.com/#!/fujitsu_uk>  [linkedin-icon.gif] <http://www.linkedin.com/company/fujitsu-uk-and-ireland>  [blogger.png] <http://blog.uk.fujitsu.com/>  [google-plus-icon.gif] <https://plus.google.com/103287532874520008913/>

**Comment by GeorgiaHCA** [comment]
@malvikasharan would you be able to review for formatting and structure?

**Comment by GeorgiaHCA** [comment]
Thanks @driscolle!

**Comment by driscolle** [comment]
Hi, could someone please perform that minor change to the file please as I don’t know how to do it.   It says I need to be on a different branch and so I request someone else to change it please to prevent me doing anything wrong.

Thanks in advance.

Emilia Driscoll
Project Manager
MIS - Solution Implementation Directorate
Fujitsu
Mob: +44 (0) 7867821962 or Internally 73 821962
Email: Emilia.Driscoll@uk.fujitsu.com<mailto:firstname.surname@xx.fujitsu.com>
Web: uk.fujitsu.com<http://uk.fujitsu.com/>
[youtube-icon.gif]<http://www.youtube.com/user/fujitsuUK> [Facebook-icon.gif] <http://www.facebook.com/fujitsuuk>  [twitter-icon.gif] <http://twitter.com/#!/fujitsu_uk>  [linkedin-icon.gif] <http://www.linkedin.com/company/fujitsu-uk-and-ireland>  [blogger.png] <http://blog.uk.fujitsu.com/>  [google-plus-icon.gif] <https://plus.google.com/103287532874520008913/>

**Comment by GeorgiaHCA** [comment]
Hey, thanks everyone! I've made the minor adjustment @driscolle so merging now. 🌟

**Pull request merged**
