### PR TITLE
worked on #641

### PR DESCRIPTION
**Pull request by akebu6**
made grammatical changes to Kendall's persona readme file

### CODE REVIEW

**Review by BrainonSilicon — APPROVED** [review]
Hi @akebu6 

Thanks so much for these changes. It looks great to me!! Let's go ahead and accept the PR.

**Comment by BrainonSilicon** [comment]
@all-contributors please add @akebu6 for content

**Comment by BrainonSilicon** [comment]
@akebu6 - I've left the `Merge Request` open if you'd like to merge it to main 🚀  Thanks for your work on this!

**Comment by akebu6** [comment]
Closed the PR, cannot believe I'm seeing this now

**Pull request merged**
