### PR TITLE
Update 20191004_summary-4-October-2019.md

### LINKED ISSUE #267: Fix broken links
## Summary

There are a few links in the repository which are broken - this is probably because we need to use relative links for one the repo is updated.

This issue will close when the links in the focus group summaries have been fixed, and we'll open a new one if any more are found.

### PR DESCRIPTION
**Pull request by ayrustogaru**
Pull Request fixes #267

### CODE REVIEW

**Comment by GeorgiaHCA** [comment]
Hey @ayrustogaru - this looks good, and it's so helpful you found where the changes need to be made. I think that you have updated the links so that they will work in your branch, but I think they will be broken when I merge them into the master branch (this is what I did too and I think why they weren't working!). Are you able to change them to relative links?

**Comment by ayrustogaru** [comment]
Oh!! Did the same mistake, huh😅!  I'll surely change them to relative links.

**Comment by GeorgiaHCA** [comment]
It's such an easy mistake to make! :) - but luckily also easy to fix :)

**Comment by ayrustogaru** [comment]
Hey!! is it okay if I close this PR and open a new one. I know it is frowned upon, but unfortunately I deleted my fork.

**Comment by GeorgiaHCA** [comment]
Hey - yes, no problem - I'm closing this PR now.

**Pull request closed without merging**
