### PR TITLE
Lottycoupat newsletter july

### PR DESCRIPTION
**Pull request by lottycoupat**

### CODE REVIEW

**Review by GeorgiaHCA — APPROVED** [review]
Heya Lotty! This looks fab - thanks for your work. I love the energised, upbeat tone. I think it would be good to add the GitHub issues as a list of tasks as well for people who don't have GitHub, and give them the option to email in - or would that be too much addititonal work?

**Comment by GeorgiaHCA** [comment]
I've been told this emoji: 💮 means "well done" but maybe it just means flower :D by this point?

**Comment by lottycoupat** [comment]
@GeorgiaHCA I have added the title of each issue along with my email if people want to find more info about the issue. I tried to add info on the issue, but thought that it ended up being a **lot** of words... What do you think?

**Comment by GeorgiaHCA** [comment]
That's a good point @lottycoupat - I think on balance you're right it's best not to overload it with information. I reckon let's go with this version and we can always respond to any feeedback :)

**Comment by GeorgiaHCA** [comment]
🎉

**Pull request merged**
