### PR TITLE
TA-feedback-03-20-2020

### PR DESCRIPTION
**Pull request by jiraslama**
Feedback from Tom on initial designs. Created a folder to add user feedback and Toms initial feedback

### CODE REVIEW

**Comment by GeorgiaHCA** [comment]
Hiya @ThomasAJR - could you review this file once CL has made changes to make sure you're happy with the content. Also would you like to be anonymous or named in the file itself? :-)

**Comment by jiraslama** [comment]
Initial Wireframes sent to Tom for review comms prior to session:

Hi Tom,
Please find a link to initial UX Deliverables iterations (subject to change) as below link:

https://blm1j3.axshare.com

This provides a reference to initial research and design thinking for the User Interface, which we can go over tomorrow as required.

I have also re-provided the initial User Interface Mockup Screens link for use to review during are session together as below link:

https://2huje4.axshare.com

I have taken the liberty of adding a series of questions relating to the user stories interface and initial prototype designs.

These questions have just been produced to act as a guide for us on Friday as attached. Which will aid are discussion / add some structure. It doesn’t all need to all be covered – there is no right or wrong answer either.

This will be a relaxed session where we can share insights together. Looking forward to it from 9:15 onwards tomorrow.

Any questions please let me know. Many thanks
Speak then.

Chris


Feedback from Tom during the afternoons session on Friday 23032020- requirement to provide a few core items to be taken into the MVP Wireframes
 
Dear Community, 
 
Please find updated initial UX feedback with summary of  key point from Toms UX Feedback session on the 20032020. I have also included the initial open questions which was used to add structure to the session.
 
Chris Legg
UX Designer 

[UX_Feedback_On_Initial_Prototypes_20032020.pdf](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4474732/UX_Feedback_On_Initial_Prototypes_20032020.pdf)
[Open_Questions_UI_Review_19032020.docx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4474735/Open_Questions_UI_Review_19032020.docx)

**Comment by jiraslama** [comment]
Dear Community, 

Please find a link to the Youtube Channel which shows a video of the:

Sprint 1 Demo 

[https://www.youtube.com/watch?v=4f6kn5HLysc](https://www.youtube.com/watch?v=4f6kn5HLysc)

Feed back from the community is very welcome.

The video along with reviewed sprint report will be uploaded onto github, where the link to the video will also be provided.

https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/141

[https://github.com/alan-turing-institute/AutisticaCitizenScience/pull/141](url)



Kind regards,

Chris Legg
UX Design

**Comment by jiraslama** [comment]
Dear Community, 

I have included the draft personas as a .ppt which can be edited / expanded upon by the community and reshared as required from feedback in are last group session. 
 
Chris Legg
[personas_process_draft.pptx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4474779/personas_process_draft.pptx)

UX Designer

**Comment by JamesSCTJ** [comment]
Hi Chris. I've put together some thoughts on the initial mock-up's. I'm happy to talk them through with you If you'd like to clarify anything.

Thanks!
James


[Wireframing thoughts.docx](https://github.com/alan-turing-institute/AutisticaCitizenScience/files/4530589/Wireframing.thoughts.docx)

**Comment by jiraslama** [comment]
Hi James, many thanks for taking the time to provide feedback. It is very useful. I will be taking it forward into the next sprint. Chris

**Comment by GeorgiaHCA** [comment]
Thomas gave me his approval of this by email so happy for it to merge

**Pull request merged**
