### PR TITLE
Create how-to-use-presentation-template.md

### PR DESCRIPTION
**Pull request by BrainonSilicon**
Created instruction guide for how to use the google slides presentation template

### CODE REVIEW

**Comment by BrainonSilicon** [comment]
Hey @GeorgiaHCA! I wrote a guide for how to use the template slides that were generated for MozFest. 

I'll create a separate PR which uploads the presentation itself later this week. 

Let me know if this is clear (@amol-prabhu would also be great if you wanted to give feedback too!)

**Comment by GeorgiaHCA** [comment]
Amazing, thanks @BrainonSilicon ! I'll take a look/review tomorrow :D

**Comment by GeorgiaHCA** [comment]
Amazing, thanks @BrainonSilicon !

**Review by GeorgiaHCA — APPROVED** [review]
Thanks for creating this @BrainonSilicon ! I think this is really clear and helpful. Go ahead and merge!

**Pull request merged**
